version: '3.9'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8020:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: developer
      WORDPRESS_DB_PASSWORD: 123456789
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: developer
      MYSQL_PASSWORD: 123456789

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8090:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
